export interface Report {
  id: number;
  image: string;
  status: string;
  category: string;
  tags: string[];
  location: string;
  description: string;
  author: string;
  date: string;
}

export const reportsData: Report[] = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Sampah',
    tags: ['Banyak Sampah'],
    location: 'Padang',
    description: 'Banyaknya sampah di area ini yang membuat warga resah',
    author: 'Budi Herman',
    date: 'October 25, 2025',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1621451537084-482c73073a0f?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Kualitas Air',
    tags: ['Air Keruh'],
    location: 'Padang Pariaman',
    description: 'Air keruh membuat warga kesulitan mendapatkan air bersih',
    author: 'Budi Herman',
    date: 'October 25, 2025',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Sampah',
    tags: ['Banyak Sampah'],
    location: 'Lembah Harau',
    description: 'Banyaknya sampah di area ini yang membuat warga resah',
    author: 'Budi Herman',
    date: 'October 25, 2025',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Sampah',
    tags: ['Banyak Sampah', 'Sampah Anorganik'],
    location: 'Bukittinggi',
    description: 'Tumpukan sampah anorganik mengganggu pemandangan dan kesehatan',
    author: 'Budi Herman',
    date: 'October 25, 2025',
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=400',
    status: 'Diverifikasi',
    category: 'Sampah',
    tags: ['Sampah Organik'],
    location: 'Payakumbuh',
    description: 'Sampah organik menumpuk di pasar tradisional',
    author: 'Siti Aminah',
    date: 'October 24, 2025',
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1583909818863-e10e28b33e73?w=400',
    status: 'Diverifikasi',
    category: 'Kualitas Air',
    tags: ['Air Bersih'],
    location: 'Solok',
    description: 'Sumber air bersih untuk masyarakat setempat',
    author: 'Ahmad Yani',
    date: 'October 24, 2025',
  },
  {
    id: 7,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
    status: 'Belum Diverifikasi',
    category: 'Penebangan Hutan',
    tags: ['Illegal Logging'],
    location: 'Agam',
    description: 'Penebangan liar di kawasan hutan lindung',
    author: 'Rahmat Hidayat',
    date: 'October 23, 2025',
  },
  {
    id: 8,
    image: 'https://images.unsplash.com/photo-1615092296061-e2ccfeb2f3d6?w=400',
    status: 'Verifikasi Ditolak',
    category: 'Pembakaran Hutan',
    tags: ['Kebakaran'],
    location: 'Lima Puluh Kota',
    description: 'Asap tebal dari pembakaran lahan',
    author: 'Dewi Sartika',
    date: 'October 23, 2025',
  },
  {
    id: 9,
    image: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Sampah',
    tags: ['Sampah Plastik'],
    location: 'Padang Panjang',
    description: 'Sampah plastik berserakan di sekitar sungai',
    author: 'Indra Gunawan',
    date: 'October 22, 2025',
  },
  {
    id: 10,
    image: 'https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=400',
    status: 'Diverifikasi',
    category: 'Kualitas Air',
    tags: ['Pencemaran Air'],
    location: 'Sawahlunto',
    description: 'Air sungai tercemar limbah industri',
    author: 'Rina Marlina',
    date: 'October 22, 2025',
  },
  {
    id: 11,
    image: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Sampah',
    tags: ['TPS Ilegal'],
    location: 'Dharmasraya',
    description: 'Pembuangan sampah sembarangan di area pemukiman',
    author: 'Zulkifli',
    date: 'October 21, 2025',
  },
  {
    id: 12,
    image: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=400',
    status: 'Belum Diverifikasi',
    category: 'Penebangan Hutan',
    tags: ['Deforestasi'],
    location: 'Sijunjung',
    description: 'Penggundulan hutan untuk lahan pertanian',
    author: 'Bambang Sutrisno',
    date: 'October 21, 2025',
  },
  {
    id: 13,
    image: 'https://images.unsplash.com/photo-1621451537084-482c73073a0f?w=400',
    status: 'Diverifikasi',
    category: 'Kualitas Air',
    tags: ['Air Keruh', 'Sedimentasi'],
    location: 'Tanah Datar',
    description: 'Keruhnya air akibat sedimentasi tinggi',
    author: 'Fitri Handayani',
    date: 'October 20, 2025',
  },
  {
    id: 14,
    image: 'https://images.unsplash.com/photo-1615092296061-e2ccfeb2f3d6?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Pembakaran Hutan',
    tags: ['Hotspot'],
    location: 'Pasaman',
    description: 'Titik api terdeteksi di kawasan hutan',
    author: 'Hendra Saputra',
    date: 'October 20, 2025',
  },
  {
    id: 15,
    image: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=400',
    status: 'Diverifikasi',
    category: 'Sampah',
    tags: ['Bank Sampah'],
    location: 'Pesisir Selatan',
    description: 'Program bank sampah berjalan dengan baik',
    author: 'Maya Anggraini',
    date: 'October 19, 2025',
  },
  {
    id: 16,
    image: 'https://images.unsplash.com/photo-1583909818863-e10e28b33e73?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Kualitas Air',
    tags: ['Sumur Bor'],
    location: 'Kepulauan Mentawai',
    description: 'Pemboran sumur air bersih untuk masyarakat',
    author: 'Joni Kusuma',
    date: 'October 19, 2025',
  },
  {
    id: 17,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
    status: 'Belum Diverifikasi',
    category: 'Penebangan Hutan',
    tags: ['HPH'],
    location: 'Pasaman Barat',
    description: 'Aktivitas HPH yang merusak ekosistem',
    author: 'Rudi Hartono',
    date: 'October 18, 2025',
  },
  {
    id: 18,
    image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=400',
    status: 'Diverifikasi',
    category: 'Sampah',
    tags: ['Daur Ulang'],
    location: 'Padang',
    description: 'Pusat daur ulang sampah plastik',
    author: 'Linda Wijaya',
    date: 'October 18, 2025',
  },
  {
    id: 19,
    image: 'https://images.unsplash.com/photo-1615092296061-e2ccfeb2f3d6?w=400',
    status: 'Verifikasi Ditolak',
    category: 'Pembakaran Hutan',
    tags: ['Pembukaan Lahan'],
    location: 'Solok Selatan',
    description: 'Pembakaran untuk pembukaan lahan baru',
    author: 'Agus Setiawan',
    date: 'October 17, 2025',
  },
  {
    id: 20,
    image: 'https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=400',
    status: 'Menunggu Verifikasi',
    category: 'Kualitas Air',
    tags: ['Limbah Pabrik'],
    location: 'Padang Pariaman',
    description: 'Pembuangan limbah pabrik ke sungai',
    author: 'Dian Permata',
    date: 'October 17, 2025',
  },
];